#!/usr/bin/bash

PACKAGE="DGTCentaurMods"
DGTCM_PATH="/opt/${PACKAGE}"

function reloadSystemd {
    systemctl daemon-reload
}

function removeInstallationDir {
    rm -rf ${DGTCM_PATH}
}

reloadSystemd

case $1 in
    purge* )
        removeInstallationDir
        exit 0
        ;;
esac
