#!/usr/bin/bash

PACKAGE="DGTCentaurMods"
DGTCM_PATH="/opt/${PACKAGE}"


function reloadSystemd {
    systemctl daemon-reload
}


function completeDGTCMremove {
    rm -rf ${DGTCM_PATH}
}


#Default actions on postrm
reloadSystemd


case $1 in
    purge* )
        completeDGTCMremove
        exit 0
        ;;
esac
