#!/usr/bin/bash

PACKAGE="DGTCentaurMods"
DGTCM_PATH="/opt/${PACKAGE}"
DATABASE="${DGTCM_PATH}/db/centaur.db"

function saveOldBeta {
    echo -e "::: Saving old beta configurations"
    mkdir -p ${DGTCM_PATH}/config/
    mkdir -p ${DGTCM_PATH}/db/
    cp /home/pi/DGTCentaurMods/config/centaur.ini ${DGTCM_PATH}/config/
    cp /home/pi/DGTCentaurMods/db/centaur.db ${DGTCM_PATH}/db/
}

case $1 in
    upgrade )
        case $2 in
            1.0-beta|1.0.1-beta)
                saveOldBeta
                ;;
        esac
esac
