#!/usr/bin/bash

PACKAGE="DGTCentaurMods"
DGTCM_PATH="/opt/${PACKAGE}"

function removePycache {    
    find ${DGTCM_PATH} | grep -E "(__pycache__|\.pyc|\.pyo$|epaper.jpg)" | xargs rm -rf
}


function stopServices {
    systemctl stop rfcomm.service
    systemctl stop centaurmods-web.service
    systemctl stop DGTCentaurMods.service
    systemctl stop var-run-sdp.path
    systemctl stop var-run-sdp.service
    systemctl stop stopDGTController.service
    systemctl stop var-run-sdp.path
}


case $1 in
    remove* )
        removePycache
        stopServices
        exit 0
        ;;
esac
