#!/usr/bin/bash

PACKAGE="DGTCentaurMods"
DGTCM_PATH="/opt/${PACKAGE}"

function removePycache {
    py3clean ${DGTCM_PATH}
    find ${DGTCM_PATH} | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
}

function stopServices {
    systemctl stop ${PACKAGE}.service
    systemctl stop ${PACKAGE}Web.service
}

case $1 in
    remove* )
        removePycache
        stopServices
        exit 0
        ;;
esac